"""
Revenue TEST dataset for the Default Workspace — fictional "TEST —" clients
with website agreements, hosting plans, charges and payments, created through
the app's own billing/client/project services so balances stay consistent.

Run (once) from apps/api:   .venv/bin/python ../../test-data/revenue_test_seed.py
Refuses to run if the manifest or any "TEST —" business already exists.

Every created row is written to revenue-test-seed.manifest.json (next to this
file) AS IT IS CREATED, so a partial run is still fully removable. Payments and
agreements also carry the seed id in their reference/notes. No emails, no
external calls: these services only write local rows + activity-log entries.
"""

import json
import sys
import uuid
from datetime import date, datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "apps" / "api"))

from sqlalchemy import select, text  # noqa: E402

from app.db import all_models  # noqa: E402,F401 — registers every model (as alembic/env.py does)
from app.db.session import SessionLocal  # noqa: E402
from app.modules.billing import service as billing  # noqa: E402
from app.modules.billing.models import HostingCharge, HostingPlan  # noqa: E402
from app.modules.billing.schemas import (  # noqa: E402
    HostingPlanCreate,
    PaymentAllocation,
    PaymentCreate,
    PaymentRefund,
    PaymentVoid,
    WebsiteAgreementUpsert,
)
from app.modules.businesses.models import Business  # noqa: E402
from app.modules.clients import service as clients_service  # noqa: E402
from app.modules.clients.schemas import ClientCreate  # noqa: E402
from app.modules.projects import service as projects_service  # noqa: E402
from app.modules.projects.schemas import ProjectCreate  # noqa: E402
from app.modules.users.models import User  # noqa: E402

SEED_ID = "TEST-SEED-REVENUE-2026-10"
HERE = Path(__file__).resolve().parent
MANIFEST = HERE / "revenue-test-seed.manifest.json"
EXPECTED_TODAY = date(2026, 10, 1)  # dates below were chosen for this "today" (workspace timezone)

manifest: dict = {
    "seed_id": SEED_ID,
    "created_at": datetime.now(timezone.utc).isoformat(),
    "workspace_id": None,
    "actor_user_id": None,
    "workspace_today": None,
    "businesses": [],
    "clients": [],
    "projects": [],
    "website_agreements": [],
    "hosting_plans": [],
    "hosting_charges": [],
    "payments": [],
    "client_checklist_items": [],
    "activity_log": [],
    "notes": "Hosting charges for LATER months may be generated by the app's hosting-billing sweep after seeding; "
    "they hang off the hosting_plans listed here (CASCADE) and must be removed with them.",
}


def save() -> None:
    MANIFEST.write_text(json.dumps(manifest, indent=2, default=str))


def main() -> None:
    if MANIFEST.exists():
        sys.exit(f"Manifest already exists ({MANIFEST}) — seed has run; refusing to duplicate.")
    db = SessionLocal()
    try:
        existing = db.scalar(select(Business).where(Business.name.like("TEST —%")))
        if existing is not None:
            sys.exit("A 'TEST —' business already exists — refusing to duplicate.")
        user = db.scalar(select(User))
        workspace_id = user.workspace_id
        today = billing.today_in_workspace(db, workspace_id)
        if today != EXPECTED_TODAY:
            sys.exit(f"Workspace today is {today}, not {EXPECTED_TODAY}; re-check the planned dates first.")
        manifest.update(workspace_id=workspace_id, actor_user_id=user.id, workspace_today=today)
        save()
        actor = user.id

        def client(name: str, slug: str, suburb: str):
            c = clients_service.create_client(
                db,
                workspace_id,
                actor,
                ClientCreate(
                    business_name=f"TEST — {name}",
                    industry="Test data",
                    website_url=f"https://{slug}.example.com",
                    suburb=suburb,
                    state="QLD",
                    billing_email=f"test+{slug}@example.com",
                ),
            )
            row = db.execute(text("select business_id from clients where id = :id"), {"id": c.id}).one()
            manifest["clients"].append(c.id)
            manifest["businesses"].append(row.business_id)
            save()
            p = projects_service.create_project(db, workspace_id, actor, ProjectCreate(client_id=c.id, name=f"TEST — {name} website"))
            manifest["projects"].append(p.id)
            save()
            return c.id, p.id

        def agreement(project_id, price, due, note=""):
            a = billing.upsert_agreement(
                db, workspace_id=workspace_id, project_id=project_id, actor_id=actor,
                data=WebsiteAgreementUpsert(price_cents=price, due_date=due, notes=f"{SEED_ID} {note}".strip()),
            )
            if a.id not in manifest["website_agreements"]:
                manifest["website_agreements"].append(a.id)
            save()
            return a.id

        def plan(project_id, fee, start, day):
            p = billing.create_hosting_plan(
                db, workspace_id=workspace_id, project_id=project_id, actor_id=actor,
                data=HostingPlanCreate(monthly_fee_cents=fee, start_date=start, billing_day=day),
            )
            manifest["hosting_plans"].append(p.id)
            save()
            # The sweep's own per-plan step (jobs/handlers.py), for THIS plan only:
            # issue every charge due on or before today, then advance next_due_date.
            plan_row = db.get(HostingPlan, p.id)
            charges = {}
            while plan_row.next_due_date <= today:
                ch = billing.generate_charge_if_missing(db, plan=plan_row)
                charges[ch.due_date] = ch.id
                manifest["hosting_charges"].append(ch.id)
                plan_row.next_due_date = billing.advance_one_month(plan_row.next_due_date, plan_row.billing_day)
            db.commit()
            save()
            return charges

        def pay(project_id, kind, alloc_id, amount, received, ref, method="Bank transfer"):
            r = billing.record_payment(
                db, workspace_id=workspace_id, actor_id=actor,
                data=PaymentCreate(
                    project_id=project_id, allocation=PaymentAllocation(type=kind, id=alloc_id), amount_cents=amount,
                    received_date=received, method=method, reference=f"{SEED_ID}-{ref}", notes=f"{SEED_ID} — fictional test payment",
                ),
            )
            manifest["payments"].append(r.id)
            save()
            return r.id

        # 1. Harbour Bakery — website build part-paid and now overdue; hosting paid.
        _, harbour = client("Harbour Bakery", "harbour-bakery", "Wynnum")
        harbour_ag = agreement(harbour, 480000, date(2026, 9, 10))
        harbour_ch = plan(harbour, 4900, date(2026, 9, 1), 5)  # Sept 5 issued; Oct 5 scheduled
        pay(harbour, "agreement", harbour_ag, 150000, date(2026, 8, 20), "harbour-deposit")
        pay(harbour, "agreement", harbour_ag, 180000, date(2026, 9, 15), "harbour-progress")  # $1,500 left, overdue
        pay(harbour, "hosting_charge", harbour_ch[date(2026, 9, 5)], 4900, date(2026, 9, 6), "harbour-host-sep")

        # 2. Northside Physio — deposit + hosting received today; balance due later this month.
        _, northside = client("Northside Physio", "northside-physio", "Chermside")
        northside_ag = agreement(northside, 320000, date(2026, 10, 20))
        northside_ch = plan(northside, 7900, date(2026, 9, 1), 1)  # Sept 1 + Oct 1 issued
        pay(northside, "hosting_charge", northside_ch[date(2026, 9, 1)], 7900, date(2026, 9, 3), "northside-host-sep")
        mistake = pay(northside, "hosting_charge", northside_ch[date(2026, 9, 1)], 79000, date(2026, 9, 3), "northside-typo")
        billing.void_payment(db, workspace_id=workspace_id, payment_id=uuid.UUID(str(mistake)), actor_id=actor,
                             data=PaymentVoid(reason=f"{SEED_ID}: entered $790 instead of $79 — reversed"))
        pay(northside, "agreement", northside_ag, 100000, date(2026, 10, 1), "northside-deposit")
        pay(northside, "hosting_charge", northside_ch[date(2026, 10, 1)], 7900, date(2026, 10, 1), "northside-host-oct", method="Card")

        # 3. Copperleaf Florist — small hosting fee; August paid, September unpaid (overdue).
        _, copperleaf = client("Copperleaf Florist", "copperleaf-florist", "Paddington")
        copper_ch = plan(copperleaf, 2900, date(2026, 8, 15), 15)  # Aug 15 + Sept 15 issued; Oct 15 scheduled
        pay(copperleaf, "hosting_charge", copper_ch[date(2026, 8, 15)], 2900, date(2026, 8, 16), "copperleaf-host-aug")

        # 4. Bluegum Plumbing — large website payment, partly refunded after a scope reduction.
        _, bluegum = client("Bluegum Plumbing", "bluegum-plumbing", "Logan")
        bluegum_ag = agreement(bluegum, 1250000, date(2026, 9, 30))
        big = pay(bluegum, "agreement", bluegum_ag, 1250000, date(2026, 9, 28), "bluegum-build")
        billing.refund_payment(db, workspace_id=workspace_id, payment_id=uuid.UUID(str(big)), actor_id=actor,
                               data=PaymentRefund(refund_amount_cents=25000, reason=f"{SEED_ID}: scope reduced by $250"))
        agreement(bluegum, 1225000, date(2026, 9, 30), "price reduced by $250 scope change")  # balance stays $0
        plan(bluegum, 9900, date(2026, 10, 2), 20)  # first charge Oct 20 (scheduled)

        # 5. Riverbend Cafe — new hosting plan, first charge unpaid (overdue).
        _, riverbend = client("Riverbend Cafe", "riverbend-cafe", "Bulimba")
        plan(riverbend, 5900, date(2026, 9, 25), 25)  # Sept 25 issued (unpaid); Oct 25 scheduled

        # Dependent rows the services created alongside (checklists, activity log).
        ids = [str(x) for k in ("clients", "projects", "website_agreements", "hosting_plans", "payments") for x in manifest[k]]
        manifest["client_checklist_items"] = [
            r[0] for r in db.execute(
                text("select id from client_checklist_items where client_id = any(cast(:c as uuid[]))"),
                {"c": [str(x) for x in manifest["clients"]]},
            )
        ]
        manifest["activity_log"] = [
            r[0] for r in db.execute(text("select id from activity_log where entity_id = any(cast(:e as uuid[]))"), {"e": ids})
        ]
        # Every other row pointing at a TEST business/client/project (found via the FKs).
        owners = {"businesses": manifest["businesses"], "clients": manifest["clients"], "projects": manifest["projects"]}
        fks = db.execute(text("""
            select tc.table_name, kcu.column_name, ccu.table_name
            from information_schema.table_constraints tc
            join information_schema.key_column_usage kcu on tc.constraint_name = kcu.constraint_name
            join information_schema.constraint_column_usage ccu on ccu.constraint_name = tc.constraint_name
            where tc.constraint_type = 'FOREIGN KEY' and ccu.table_name in ('businesses','clients','projects')"""))
        dependents: dict = {}
        for table, column, ref in fks:
            rows = [r[0] for r in db.execute(
                text(f'select id from "{table}" where "{column}" = any(cast(:ids as uuid[]))'),
                {"ids": [str(x) for x in owners[ref]]},
            )]
            if rows:
                dependents.setdefault(table, sorted({*dependents.get(table, []), *map(str, rows)}))
        manifest["dependents_by_fk"] = dependents
        save()
        print(f"Seeded. Manifest: {MANIFEST}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
