"""website approval workflow

Revision ID: 6742373b79d7
Revises: a40797583bc7
Create Date: 2026-08-26 18:39:49.083798

Phase 6 Task 3 — a formal DRAFT -> INTERNAL_REVIEW -> CLIENT_REVIEW ->
CHANGES_REQUESTED -> APPROVED -> READY_TO_DEPLOY -> DEPLOYED lifecycle
for one website version, layered on top of the existing boolean
approval checkpoints rather than replacing them. See
app/modules/websites/models.py's WebsiteWorkflowStatus docstring for
the full transition graph and app/modules/websites/service.py's
ALLOWED_TRANSITIONS for where it's enforced.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6742373b79d7'
down_revision: Union[str, None] = 'a40797583bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_workflow_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'READY_TO_DEPLOY', 'DEPLOYED', name='website_workflow_status'), nullable=False),
    sa.Column('to_status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'READY_TO_DEPLOY', 'DEPLOYED', name='website_workflow_status'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'websites',
        sa.Column(
            'workflow_status',
            sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'READY_TO_DEPLOY', 'DEPLOYED', name='website_workflow_status'),
            server_default='DRAFT',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    # The autogenerate diff also proposed dropping four indexes on
    # email_sends/meeting_attendees/meeting_reminders — pre-existing
    # drift between those models and their own migrations, unrelated to
    # this change. Left untouched here; not this migration's job to fix.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'workflow_status')
    op.drop_table('website_workflow_transitions')
    # ### end Alembic commands ###
