"""daily action engine

Revision ID: 74720e3bfd52
Revises: 6742373b79d7
Create Date: 2026-08-27 07:32:08.863252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74720e3bfd52'
down_revision: Union[str, None] = '6742373b79d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_action_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_action_runs_generated_at'), 'daily_action_runs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_daily_action_runs_workspace_id'), 'daily_action_runs', ['workspace_id'], unique=False)
    op.create_table('action_queue_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('HOT_LEAD_UNCONTACTED', 'FOLLOW_UP_OVERDUE', 'MEETING_APPROACHING', 'PROPOSAL_AWAITING_RESPONSE', 'CLIENT_ASSETS_MISSING', 'WEBSITE_REVISION_AWAITING_APPROVAL', 'DEPLOYMENT_FAILED', 'PROJECT_DEADLINE_APPROACHING', name='action_kind'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('opportunity_score', sa.Integer(), nullable=False),
    sa.Column('deadline_score', sa.Integer(), nullable=False),
    sa.Column('pipeline_value_cents', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['daily_action_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_queue_items_run_id'), 'action_queue_items', ['run_id'], unique=False)
    op.create_index(op.f('ix_action_queue_items_workspace_id'), 'action_queue_items', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
    # Note: autogenerate also proposed dropping ix_email_sends_lead_id,
    # ix_email_sends_outreach_message_id, ix_meeting_attendees_meeting_id,
    # and ix_meeting_reminders_meeting_id — pre-existing drift between
    # this dev DB and the current models, unrelated to this migration.
    # Left alone here; a separate migration should reconcile them.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_queue_items_workspace_id'), table_name='action_queue_items')
    op.drop_index(op.f('ix_action_queue_items_run_id'), table_name='action_queue_items')
    op.drop_table('action_queue_items')
    op.drop_index(op.f('ix_daily_action_runs_workspace_id'), table_name='daily_action_runs')
    op.drop_index(op.f('ix_daily_action_runs_generated_at'), table_name='daily_action_runs')
    op.drop_table('daily_action_runs')
    # ### end Alembic commands ###
