"""preview links

Revision ID: 7e4994ec399a
Revises: 731a8a798e83
Create Date: 2026-08-26 14:07:08.898388

Roadmap M5's last open item — "a secure shareable client-preview link
with feedback capture" (docs/04_ROADMAP.md, docs/01_REQUIREMENTS.md
stage 18). See app/modules/previews/models.py's PreviewLink docstring.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4994ec399a'
down_revision: Union[str, None] = '731a8a798e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preview_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_suffix', sa.String(length=8), nullable=False),
    sa.Column('audience', sa.Enum('CLIENT', 'INTERNAL', name='preview_audience'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preview_links_token_hash'), 'preview_links', ['token_hash'], unique=True)
    # ### end Alembic commands ###
    # The autogenerate diff also proposed dropping four indexes on
    # email_sends/meeting_attendees/meeting_reminders — pre-existing
    # drift between those models and their own migrations, unrelated to
    # this change. Left untouched here; not this migration's job to fix.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preview_links_token_hash'), table_name='preview_links')
    op.drop_table('preview_links')
    # ### end Alembic commands ###
