"""website feedback

Revision ID: a40797583bc7
Revises: 7e4994ec399a
Create Date: 2026-08-26 18:29:09.679573

Phase 6 Task 2 — client feedback captured directly on a website preview
(comment/change request/approval/rejection/general), always tied to the
project, the exact website version, the page/section where possible,
who left it, when, and its resolution status. See
app/modules/website_feedback/models.py's WebsiteFeedback docstring.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40797583bc7'
down_revision: Union[str, None] = '7e4994ec399a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=False),
    sa.Column('preview_link_id', sa.UUID(), nullable=True),
    sa.Column('page_slug', sa.String(length=255), nullable=True),
    sa.Column('section_id', sa.String(length=120), nullable=True),
    sa.Column('feedback_type', sa.Enum('COMMENT', 'CHANGE_REQUEST', 'APPROVAL', 'REJECTION', 'GENERAL', name='website_feedback_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='website_feedback_status'), server_default='OPEN', nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preview_link_id'], ['preview_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # The autogenerate diff also proposed dropping four indexes on
    # email_sends/meeting_attendees/meeting_reminders — pre-existing
    # drift between those models and their own migrations, unrelated to
    # this change. Left untouched here; not this migration's job to fix.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_feedback')
    # ### end Alembic commands ###
